<?php

/**
 * @File
 * hook implementations for custom_domain_verifier module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * @implements hook_form_FORM_ID_alter for email domain verification.
 */
function custom_domain_verifier_form_user_register_form_alter(array &$form, FormStateInterface $form_state) {
  $form['#validate'][] = 'custom_email_validator';
}

/**
 * Custom function to validated email.
 */
function custom_email_validator(array &$form, FormStateInterface $form_state) {
  $email = $form_state->getValue('mail');
  $allowed_domain = \Drupal::config('custom_domain_verifier.settings')->get('domain');
  
  if (strpos($email, $allowed_domain) === false) {
    $form_state->setErrorByName('mail', t('Only email address with domain @domain is allowed.', 
    ['@domain' => $allowed_domain]));
  }
}

/**
 * Implements hook_uninstall for custom_domain_verifier module.
 */
function custom_domain_verifier_uninstall() {
  // Delete the custom_domain_verifier.settings file.
  $config_path = \Drupal::configFactory()->getEditable('custom_domain_verifier.settings');
  if ($config_path->isNew()) {
    $config_path->delete();
    \Drupal::messenger()->addMessage(t('custom_domain_verifier.settings file has been deleted.'));
  }

}