<?php

/**
 * @file
 * Primary module hooks for custom_default_role module.
 */

 use Drupal\Core\Form\FormStateInterface;

/**
 * @implements hook_form_FORM_ID_alter for email domain verification.
 */
function custom_default_role_form_user_register_form_alter(array &$form, FormStateInterface $form_state) {
  // Getting custom_default_role.settings configuration.
  $config = \Drupal::configFactory()->getEditable('custom_default_role.settings');
  
  if ($config) {
    $default_role = $config->get('role');
    $form['account']['roles'][$default_role] = [
      '#default_value' => true,
      '#disabled' => true,
    ];
  }
}

/**
 * Implements hook_uninstall for custom_default_role module.
 */
function custom_default_role_uninstall() {
  // Delete the custom_domain_verifier.settings file.
  $config_path = \Drupal::configFactory()->getEditable('custom_default_role.settings');
  if ($config_path->isNew()) {
    $config_path->delete();
    \Drupal::messenger()->addMessage(t('custom_default_role.settings file has been deleted.'));
  }

}